import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        surface: '#f9f9f9',
        'on-secondary-container': '#151c27',
        'on-tertiary-fixed-variant': '#e0e2e6',
        'surface-container-low': '#f3f3f4',
        secondary: '#585f6c',
        outline: '#777777',
        'outline-variant': '#c6c6c6',
        'on-primary': '#e2e2e2',
        'tertiary-container': '#727578',
        'inverse-primary': '#c6c6c6',
        'primary-fixed-dim': '#474747',
        'on-surface-variant': '#474747',
        'on-primary-fixed-variant': '#e2e2e2',
        'surface-container': '#eeeeee',
        'surface-dim': '#dadada',
        'on-background': '#1a1c1c',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'inverse-on-surface': '#f0f1f1',
        'on-tertiary': '#e0e2e6',
        'surface-tint': '#5e5e5e',
        'on-secondary-fixed': '#151c27',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'surface-variant': '#e2e2e2',
        'surface-container-highest': '#e2e2e2',
        'tertiary-fixed-dim': '#44474a',
        'secondary-container': '#ced4e4',
        'inverse-surface': '#2f3131',
        'on-primary-fixed': '#ffffff',
        primary: '#000000',
        'on-secondary-fixed-variant': '#353c48',
        'surface-container-high': '#e8e8e8',
        'on-error': '#ffffff',
        background: '#f9f9f9',
        'on-primary-container': '#ffffff',
        'primary-container': '#3b3b3b',
        'secondary-fixed-dim': '#a4abbb',
        tertiary: '#383c3f',
        'secondary-fixed': '#c0c7d6',
        'on-surface': '#1a1c1c',
        'tertiary-fixed': '#5c5f62',
        'on-error-container': '#410002',
        'on-tertiary-fixed': '#ffffff',
        'primary-fixed': '#5e5e5e',
        'surface-bright': '#f9f9f9',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      boxShadow: {
        soft: '0 20px 60px -32px rgba(0,0,0,0.18)',
      },
    },
  },
} satisfies Config
